//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HeroList
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> YearCreated { get; set; }
        public string Medium { get; set; }
        public string Founder { get; set; }
        public string Picture { get; set; }
    }
}
